name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there! This is mainly a private project. I am not currently accepting pull requests, but feel free to ask any questions in Issues. '
        pr-message: 'Hi there! This is mainly a private project. I am not currently accepting pull requests, but feel free to ask any questions in Issues.'
